### ISSUE TITLE
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'. Did you mean: 'get_feature_names_out'?

### ISSUE THREAD

**Issue by PankajKarki** [MaartenGr/KeyBERT#155]
>>> kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/env/lib/python3.10/site-packages/keybert/_model.py", line 110, in extract_keywords
    keywords = self._extract_keywords_single_doc(doc=docs,
  File "/home//env/lib/python3.10/site-packages/keybert/_model.py", line 172, in _extract_keywords_single_doc
    candidates = count.get_feature_names()
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'. Did you mean: 'get_feature_names_out'?

**Comment by MaartenGr** [comment]
Are you using the most recent version of KeyBERT? I believe this was fixed in one of its newest versions. It should work in v0.7.
