### ISSUE TITLE
ImportError: cannot import name 'SAVE_STATE_WARNING'

### ISSUE THREAD

**Issue by desairahul49** [MaartenGr/KeyBERT#38]
Fresh Installation of keybert
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (C:\Users\rahul.desai\Anaconda3\lib\site-packages\torch\optim\lr_scheduler.py)

**Comment by MaartenGr** [comment]
This usually happens if an incorrect version of Pytorch is installed. How did you install KeyBERT? Could you also share the versions of the installed packages?

**Comment by desairahul49** [comment]
Have installed KeyBERT using below command.
pip install keybert[all].
And Pytorch 1.8.1 is installed in the system

**Comment by MaartenGr** [comment]
Ah, then there is the culprit. Pytorch should be `"torch>=1.4.0,<1.7.1"`. So if you downgrade to one of those versions, it should work.

**Comment by desairahul49** [comment]
Thanks for the information it worked with Pytorch 1.7.0
