### ISSUE TITLE
Failed to use KeyphraseCountVectorizer with Keybert 0.7.0

### ISSUE THREAD

**Issue by homepsyc** [MaartenGr/KeyBERT#141]
KeyphraseCountVectorizer used to work with Keybert but now with 0.7.0 it failed with  highlight_document():

```
def highlight_document(
    doc: str, keywords: List[Tuple[str, float]], vectorizer: CountVectorizer
):
    keywords_only = [keyword for keyword, _ in keywords]
    max_len = vectorizer.ngram_range[1]
```

Exception says:
```
AttributeError: 'KeyphraseCountVectorizer' object has no attribute 'ngram_range'
```
which is expected for KeyphraseCountVectorizer.

Please kindly advise, thanks.

**Comment by MaartenGr** [comment]
Could you share your entire code for getting this error? Seeing your code and having a reproducible example would help in identifying what is exactly happening here.

**Comment by homepsyc** [comment]
```
from keyphrase_vectorizers import KeyphraseCountVectorizer
vectorizer = KeyphraseCountVectorizer()
keyword4 = model.extract_keywords(doc, vectorizer=vectorizer, highlight=True)
```
![Screenshot from 2022-11-16 16-43-12](https://user-images.githubusercontent.com/6670511/202131507-beca8861-8aa0-484d-b906-32149c0ad70a.png)

Thanks @MaartenGr

**Comment by MaartenGr** [comment]
Ah, it seems that since KeyphraseCountVectorizer discovers its own n-gram range and because of that it does not have a `ngram_range` attribute. Moreover, since it is technically not a scikit-learn CountVectorizer other function, like `build_tokenizer()` are missing. Unfortunately, there is no quick fix for this as it may require large changes on either side.
